import pandas as pd
# data=pd.Series([2, 4, -5, 9, -3], index=["a", "b", "c", "d", "e"])
# print("Data type",data.dtype)
# print("Data size",data.size)
# print("Data index",data.index)
# print("First element in series is",data[0])
# print("First element in series is",data["a"])
# print("Largest number is",data.max())
# print("Sum of all element is",data.sum())
# print("Mean of all element is",data.mean())
# print("Standard deviation in data is",data.std())
# print("Median deviation in data is",data.median())
# print("Top three numbers in data is\n",data.nlargest(3))


data_string=pd.Series(["你好", "Python", "Pandas"], index=["a", "b", "c"])
print("=============")
print(data_string.str.lower())
print("=============")
print(data_string.str.cat(sep="-"))
print("=============")
print(data_string.str.contains("P"))
print("=============")
print(data_string.str.replace("P","p"))